spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pret_jv_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger
